### ISSUE TITLE
Wrong relation IDs in mined rules and how to read the rules?

### ISSUE THREAD

**Issue by yangyang-pro** [XiaojuanTang/RulE#4]
Hi @XiaojuanTang 

Thanks for the nice work.

1)
I just found that the relation IDs in the `mined_rules.txt` file are a bit strange.

E.g. In the family dataset, there are only 12 relations according to the `relations.dict` file. 
However, in its `mined_rules.txt` file, the number of relations is 24 (the largest ID is 23).
This problem also appears in other datasets.

Could you explain why?

2)
How should we read the mined rules?

I see there are only relation IDs in these mined rules. But how do we know the order of the entities in these relations?
I think it's clear in your paper

> born_in(x, y) ∧ city_of(y, z) → nationality(x, z)

But how do we read what x, y, z is in the `mined_rules.txt` file?

Thanks in advance for your response.

**Comment by XiaojuanTang** [comment]
Apologies for the delayed response.
	1. In our paper, we focus on chain rules, which already cover common logical rules in KGs such as symmetry, composition, and hierarchy (see Appendix 16.2: Data Processing). For non-chain-like rules, we transform them by inverting some relations. The mined_rules.txt file contains transformed chain rules that include inverse relations, leading to the increased number of relation IDs (i.e., 24).
	2. Based on the definition of chain rules, a chain rule is a logical rule where relations are sequentially connected through shared variables, forming a “chain-like” structure.  It takes the general form: $r_1(x, y) \land r_2(y, z) \land \dots \land r_n(w, v) \rightarrow r(x, v)$, where $x, y, z, w, v$ are entities, and $r_1, r_2, \dots, r_n, r$ are relations. The body of the rule (the left-hand side) is a conjunction of relations, and the head of the rule (the right-hand side) is the inferred relation.
	Thus, the order of entities in these chain-like rules follows the default sequence: e.g., x-y-y-z → x-z. We use RNN to model the relationship between relation embedding and rule embedding, ensuring the correct order between relations.

**Comment by yangyang-pro** [comment]
Thank you for your reply!
